// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbvexnlawjzgjjazgmgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJidmV4bmxhd2p6Z2pqYXpnbWdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0ODEzMjksImV4cCI6MjA2NTA1NzMyOX0.8auffef2Bg9qUNBzPl28xeYBNxD8zGCS88ba0C15OGY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);